security:
#password cf client will use when interacting with broker
  user.password: ${user.password}
hbase:
  brokergroupname: intel
  provided.params: ${hadoop.provided.params:{}}
cf:
  #name of service in cloud foundry catalog
  servicename: ${cf.catalog.servicename:hbase}
  #id of service in cloud foundry catalog
  serviceid: ${cf.catalog.serviceid:hbase}
  #id of base plan in cloud foundry catalog
  baseId: ${BASE_GUID:}
zk:
  cluster: "localhost"
  metadatanode: "/broker"
metadata:
  imageUrl: ${IMAGE_URL:}
