security:
  #password cf client will use when interacting with broker
  user.password: ${user.password}
hbase:
  #encoded hadoop configuration files for hbase
  provided.zip: ${hadoop.provided.zip:}
store:
  #optional parameter to configure zookeeper-store
  path: ${broker.store.znode:/broker/hbase/metadata}
cf:
  #name of service in cloud foundry catalog
  servicename: ${cf.catalog.servicename:hbase}
  #id of service in cloud foundry catalog
  serviceid: ${cf.catalog.serviceid:hbase}
  #id of base plan in cloud foundry catalog
  baseId: ${BASE_GUID:}
metadata:
  #encoded image file viewed in marketplace
  imageUrl: ${IMAGE_URL:}
